version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:8080"  # Map local port 3000 to container port 8080
    environment:
      - NODE_ENV=development
      - PORT=8080
    volumes:
      - .:/app
      - /app/node_modules  # Exclude node_modules from volume mount
    command: bun --watch src/index.ts  # Use watch mode for development
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a database service if needed later
  # postgres:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: lavago_dev
  #     POSTGRES_USER: lavago
  #     POSTGRES_PASSWORD: lavago123
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U lavago"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

# volumes:
#   postgres_data: 